version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5-stretch

    steps:
      - checkout

      - run: sudo apt-get install libxtst-dev libpng++-dev build-essential

      - run:
          name: instalar pacotes
          command: npm i

      - run:
          name: lint
          command: npm run lint

      - run:
          name: testes
          command: npm run test-unit-ci

      - add_ssh_keys:
          fingerprints:
            - "db:ad:39:40:49:f2:20:e0:a8:73:47:15:c5:d1:86:b4"

      - run:
          name: Release tag
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            echo $(echo ${CIRCLE_SHA1} | cut -c -7) > last_tag
            git tag $(echo ${CIRCLE_SHA1} | cut -c -7)
            git push origin $(echo ${CIRCLE_SHA1} | cut -c -7)
